import { LRUCache } from 'lru-cache'

export const cache = new LRUCache({ max: 1_000 })
export const locale = 'en-US'

export { default as asyncValue } from './src/async-value'
export { default as bytes } from './src/bytes'
export { default as copy } from './src/copy'
export { default as createBlob } from './src/create-blob'
export { default as delay } from './src/delay'
export { default as EndlessIcons } from './src/endless-icons'
export { default as FilterIcons } from './src/filter-icons'
export { default as getAll } from './src/get-all'
export { default as getBookmarkIcons } from './src/get-bookmark-icons'
export { default as Grid } from './src/grid'
export { default as HoverCard } from './src/hover-card'
export { default as IconButton } from './src/icon-button'
export { default as JSZip } from './src/jszip'
export { default as Listbox } from './src/listbox'
export { default as MotionPluralize } from './src/motion-pluralize'
export { default as openObjectURL } from './src/open-object-url'
export { default as Page } from './src/page'
export { default as pluralize } from './src/pluralize'
export * from './src/recently-viewed-icons'
export { default as relativeTime } from './src/relative-time'
export { default as saveAs } from './src/save-as'
export { default as SearchIcons } from './src/search-icons'
export { default as Theme } from './src/theme'
export { default as toNumber } from './src/to-number'
export { default as toast } from './src/toast'
export { default as wrapIcon } from './src/wrap-icon'
export { default as wrapIcons } from './src/wrap-icons'

export { default as is } from '@sindresorhus/is'
export { useCreation as createMemo, useUpdate as rerender } from 'ahooks'
export { default as has } from 'has-values'
export { default as mime } from 'mime/lite'
export { default as clone } from 'rfdc/default'
